### ISSUE TITLE
Errors with intervalId=300 seconds

### ISSUE THREAD

**Issue by shay9748** [vmware/pyvmomi#783] opened 2019-04-09 23:07 UTC
I tried to extract data from the past 5 minutes and changed the intervalId from 20 seconds to 300 seconds but it gave me the following error. What exactly is going on? 

Code
//counterID was correct since the code works for 20 seconds intervalId but throws errors for
when I change it to 300 seconds
metricId = vim.PerformanceManager.MetricId(counterId=counterId, instance="*")
query = vim.PerformanceManager.QuerySpec(intervalId=300, entity=vm, metricId=[metricId]

The errors I see:-
   perfResults = perfManager.QueryPerf(querySpec=[query])
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 706, in <lambda>
  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: querySpec[0].intervalId',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'querySpec[0].intervalId'
}

**Comment by pgbidkar** [comment] 2019-04-10 12:08
Hi @shay9748 , Please can you share your code snippet. I am not able to reproduce issue with 'internalId=300'

```
query = vim.PerformanceManager.QuerySpec(intervalId=300,
                                                 maxSample=1,
                                                 entity=host,
                                                 metricId=[metricId],
                                                 startTime=startTime,
                                                 endTime=endTime)
```

but if I set 'internalId=1' Then I get the same exception 
```
Caught vmodl fault : A specified parameter was not correct: querySpec.interval
```

**Comment by shay9748** [comment] 2019-04-10 13:40
Hey @pgbidkar . Here is the code I used:-

`metricId = vim.PerformanceManager.MetricId(counterId=1, instance="")`
`query = vim.PerformanceManager.QuerySpec(entity=vm, metricId=[metricId],intervalId = 300, maxSample=1)`
`perfResults = perfManager.QueryPerf(querySpec=[query])`

**Comment by shay9748** [comment] 2019-04-10 14:19
Actually if you meant by entire code, this is what I used:-

```
#!/usr/bin/env python

from __future__ import division
from dateutil.relativedelta import relativedelta, MO
import dateutil.parser
from pyVmomi import vim,vmodl
from tools import cli
from pyVim.connect import SmartConnectNoSSL, Disconnect
import atexit
import sys
import json
import subprocess
import pstats
import datetime

global si

def make_ssl_connection( ip,username,password):
    error_seen = False
    si = ''
    try:
        si = SmartConnectNoSSL(
            host = ip,
            user = username,
            pwd = password,port = 443)
        atexit.register(Disconnect, si)
    except Exception as e:
        error_seen = True

    return si, error_seen

def PrintVmInfo(vm, content, perf_dict ):
    perfManager = content.perfManager

    metricId = vim.PerformanceManager.MetricId(counterId=1, instance="")
    query = vim.PerformanceManager.QuerySpec(entity=vm, metricId=[metricId],\
intervalId = 300, maxSample=1)
    perfResults = perfManager.QueryPerf(querySpec=[query])
    if perfResults:
        print(perfResults)
    else:
        print('ERROR: Performance results empty.  TIP: Check time drift on source and vCenter server')
        print('Troubleshooting info:')
        print(query)
        exit()

def main():

        args = cli.get_args()

        # Connect to the host without SSL signing
        si, error_seen = make_ssl_connection(args.host,args.user,args.password)
        if error_seen == True:
              continue

        content = si.RetrieveContent()
        perfManager = content.perfManager

            # create a mapping from performance stats to their counterIDs
            counterInfo = {}
            for c in perfManager.perfCounter:
                    fullName = c.groupInfo.key + "." + c.nameInfo.key + "." + c.rollupType
                    counterInfo[fullName] = c.key

            # create a list of vim.VirtualMachine objects so
            # that we can query them for statistics
            container = content.rootFolder
            viewType = [vim.VirtualMachine]
            recursive = True
            containerView = content.viewManager.CreateContainerView(container,viewType,recursive)
            children = containerView.view
            # Loop through all the VMs
            for child in children:
                    # Get all available metric IDs for this VM

                    # Using the IDs form a list of MetricId
                    # objects for building the Query Spec
                    #1=cpu usage -> counter-ID for cpu usage
                    counterIDs = [1]  
                    metricIDs = [vim.PerformanceManager.MetricId(counterId=c, instance="*")
                                                                     for c in counterIDs]
                    PrintVmInfo(child, content, counterInfo)

if __name__ == "__main__":
    main()
```

**Comment by pgbidkar** [comment] 2019-04-11 06:35
Hi @shay9748 , I am not able to reproduce the issue. Please can you try this code?

```
import argparse
import atexit
import getpass
import datetime

from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim

def main():
    """
   Simple command-line program demonstrating vSphere perfManager API
   """
    import ssl
    args = get_args()
    try:
        service_instance = connect.SmartConnect(VCIP,
                                                VCUserName,
                                                VCPassword,
                                                sslContext=ssl._create_unverified_context())
        if not service_instance:
            print("Could not connect to the specified host using specified "
                  "username and password")
            return -1

        atexit.register(connect.Disconnect, service_instance)

        content = service_instance.RetrieveContent()

        search_index = content.searchIndex
        # quick/dirty way to find an ESXi host
        host = search_index.FindByDnsName(dnsName=ESXHOst, vmSearch=False)

        perfManager = content.perfManager
        metricId = vim.PerformanceManager.MetricId(counterId=1, instance="")
        startTime = datetime.datetime.now() - datetime.timedelta(hours=1)
        endTime = datetime.datetime.now()

        query = vim.PerformanceManager.QuerySpec(intervalId=300,
                                                 maxSample=1,
                                                 entity=host,
                                                 metricId=[metricId],
                                                 startTime=startTime,
                                                 endTime=endTime)
        print(perfManager.QueryPerfCounter([1]))
        print(perfManager.QueryPerf(querySpec=[query]))

    except vmodl.MethodFault as e:
        print("Caught vmodl fault : " + e.msg)
        return -1
    except Exception as e:
        print("Caught exception : " + str(e))
        return -1

    return 0

# Start program
if __name__ == "__main__":
    main()
```

**Comment by mmqzlj** [comment] 2019-05-24 03:19
i got the same problem

**Comment by pgbidkar** [comment] 2019-05-24 05:21
Hi @shay9748 , any updates on this? did you get chance to try the code snippet I shared? did it fix your issue?

Thanks

**Comment by pgbidkar** [comment] 2019-08-06 11:50
Closing the issue. Please reopen if issue is still seen
Thanks

**Closed by pgbidkar** 2019-08-06 11:50 UTC
