### ISSUE TITLE
EnvironmentBrowser.QueryConfigOption raise pyVmomi.SoapAdapter.ParserError when esx is 6.5

### ISSUE THREAD

**Issue by solashR** [vmware/pyvmomi#514] opened 2017-02-22 15:54 UTC
after upgrade the ESX to 6.5
i have tried to call EnvironmentBrowser.QueryConfigOption but it raise pyVmomi.SoapAdapter.ParserError

tried upgrade pyvmomi also to ver 6.5 - same result

with msg: pyVmomi.SoapAdapter.ParserError: 'xml document: <httplib.HTTPResponse instance at 0x37e14d0> parse error at: line:7, col:618371

attached: the entire xml response
[pyvmomi_parse_error (2).txt](https://github.com/vmware/pyvmomi/files/794012/pyvmomi_parse_error.2.txt)

thanks

**Comment by prziborowski** [comment] 2017-02-22 22:48
I don't have an answer to this issue, but I will state that pyvmomi 6.5 is definitely needed if you want to use that API on an ESXi 6.5 host.

**Comment by vikentiik** [comment] 2017-02-23 17:51
I have the same issue, no idea how to work around it (pyvmomi 6.5, VCSA 6.5, ESX 6.5, all updated).
For me the error is this:
ParserError: 'xml document: <httplib.HTTPResponse instance at 0x7ff2a2a30128> parse error at: line:7, col:617203'

I tried to look by the offset but it doesn't fall onto anything suspicious to me. I tried to find differences between the definition of that structure in API references for 6.0 and 6.5 and didn't find any (BoolOption autoDetectAvailable inside VirtualSCSIPassthroughDeviceBackingOption).

I am probably not interpreting the offset correctly. It falls onto the middle of opening tag of the defaultValue element...

[My xml sample](https://github.com/vmware/pyvmomi/files/797257/pe.txt)

**Comment by vikentiik** [comment] 2017-02-23 18:22
On a second try I probably found sort of an issue. This way the offset falls on the end of `<type>VirtualNVDIMM</type>`

The two virtualDeviceOption types listed below seem to be new in vSphere 6.5.
...python2.7/site-packages/pyVmomi/ServerObjects.py does not mention them. 
I'm guessing that it should.

`<virtualDeviceOption>
<type>VirtualNVDIMM</type>
<controllerType>VirtualNVDIMMController</controllerType>
<autoAssignController>
<supported>false</supported>
<defaultValue>false</defaultValue>
</autoAssignController>
<backingOption>
<type>VirtualNVDIMMBackingInfo</type>
</backingOption>
<defaultBackingOptionIndex>0</defaultBackingOptionIndex>
<deprecated>false</deprecated>
<plugAndPlay>false</plugAndPlay>
<hotRemoveSupported>false</hotRemoveSupported>
</virtualDeviceOption>`

`<virtualDeviceOption xsi:type="VirtualControllerOption">
<type>VirtualNVDIMMController</type>
<autoAssignController>
<supported>false</supported>
<defaultValue>false</defaultValue>
</autoAssignController>
<deprecated>false</deprecated>
<plugAndPlay>false</plugAndPlay>
<hotRemoveSupported>false</hotRemoveSupported>
<devices>
<min>0</min>
<max>64</max>
<defaultValue>0</defaultValue>
</devices>
<supportedDevice>VirtualNVDIMMOption</supportedDevice>
</virtualDeviceOption>`

**Comment by tianhao64** [comment] 2017-02-23 18:24
@vikentiik, @elasti-rans Can you share your script so I can reproduce this?

**Comment by vikentiik** [comment] 2017-02-23 18:39
See below. Please, disregard the wrapper. I couldn't figure out quickly enough how to do without it. 
It is unlikely that the original reporter has that wrapper as well, yet we have the same issue.

I connect, get a cluster, and make the call, that's all there is.

import ssl
s = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
s.verify_mode = ssl.CERT_NONE
import pyvmomi_wrapper
client = pyvmomi_wrapper.Client(vcenter_fqdn, "Administrator@vsphere.local", vcenter_password, sslContext=s)
cluster = client.get_host_clusters()[-1]
cluster.environmentBrowser.QueryConfigOption()

**Comment by tianhao64** [comment] 2017-02-23 18:44
Thanks I am able to reproduce this now.

**Comment by tianhao64** [comment] 2017-02-23 20:44
@vikentiik Thanks for the investigation. It seems the server shouldn't return 'VirtualNVDIMM' field. It seems to be a vsphere bug. Let me follow up with the corresponding engineering team for a potential solution/workaround.

**Comment by vikentiik** [comment] 2017-02-26 12:57
@tianhao64, @elasti-rans, @prziborowski, I worked around this:

To the file `...lib/python2.7/site-packages/pyVmomi/ServerObjects.py` I added the following definitions:

> CreateDataType("vim.vm.device.VirtualNVDIMM", "VirtualNVDIMM", "vim.vm.device.VirtualDevice", "vim.version.version11", None)
> CreateDataType("vim.vm.device.VirtualNVDIMM.DeviceBackingInfo", "VirtualNVDIMMBackingInfo", "vim.vm.device.VirtualDevice.DeviceBackingInfo", "vim.version.version11", None)
> CreateDataType("vim.vm.device.VirtualNVDIMMController", "VirtualNVDIMMController", "vim.vm.device.VirtualController", "vim.version.version11", None)
> CreateDataType("vim.vm.device.VirtualNVDIMMOption", "VirtualNVDIMMOption", "vim.vm.device.VirtualDeviceOption", "vim.version.version11", None)

The call now runs fine. My routines run fine.
However, strictly speaking I cannot know what I broke, so...

**Comment by tianhao64** [comment] 2017-02-27 17:51
@vikentiik Glad to hear you are unblocked. 
Yes adding the missing type can be a temporary workaround. I am still waiting the feature team's response on what should be the fix or long term solution.

**Comment by nordicmachine** [comment] 2017-04-05 13:38
@tianhao64 Any update on this?  We've run into this while testing an upgrade to VCSA 6.5, ESXi 6.5 and were wondering on an official fix rather than having to monkey patch this in.

**Comment by vikentiik** [comment] 2017-04-05 15:24
@nordicmachine maybe try running your code on ESX? I once heard pyvmomi there may often be in a better shape.

**Comment by tianhao64** [comment] 2017-04-05 15:31
@nordicmachine There is no easy solution on vSphere side to hide these device types. Perhaps we can do something like #398 to ignore these types and let deserialization to pass. I haven't find an opportunity to work on this yet. Will try to get to it as soon as I can.

**Comment by wiggin15** [comment] 2018-09-25 08:37
I think that this is fixed by 6aeb7dc6a8677a39b54a2d7a3f32c3b8a7f4e9cc. The missing types (e.g. `VirtualNVDIMM`) were finally added.

**Closed** 2023-01-26 19:03 UTC
Labels: bug
