### ISSUE TITLE
Version 6.7.0

### ISSUE THREAD

**Issue by cpollard0** [vmware/pyvmomi#716] opened 2018-09-06 08:43 UTC
What happened to version 6.7.0?

**Comment by tianhao64** [comment] 2018-09-06 17:01
@cpollard0 We have to fix a critical issue in version 6.7.0 binding. I pushed a new commit (6.7.0.2018.9) which override the previous one. It contains the 6.7.0 GA binding with the fix. Can you please re-sync your repo and pip install upgrade pyvmomi to get the latest change?

**Comment by saenzpa** [comment] 2018-09-06 20:26
@tianhao64 The problem is that 24 hours ago having a fixed requirement of pyvmomi==6.7.0 would work. That package simply dissapeared overnight. Critical issue or not, you probably broke a lot of people's workflows with that change.

**Comment by tianhao64** [comment] 2018-09-07 01:34
@saenzpa I see. You are right. I missed this case when changing the packages on pypi. Apologies for the mistake.
I just attempted to recover the package on pypi, but it seems pypi doesn't allow re-upload the same package...

**Comment by thomasshanks** [comment] 2018-09-12 05:43
How did the upgrade from 6.7.0 to 6.7.0.2018.9 remove EnableMethods and DisableMethods?  We need those.  Please repost 6.7.0.

**Comment by tianhao64** [comment] 2018-09-12 06:39
@thomasshanks Those two methods were included by mistake. The issue is fixed in the new version.

**Comment by hashbou** [comment] 2018-09-12 09:11
> @saenzpa I see. You are right. I missed this case when changing the packages on pypi. Apologies for the mistake.
> I just attempted to recover the package on pypi, but it seems pypi doesn't allow re-upload the same package...

Are you going to investigate in finding a solution to re-upload 6.7.0 to pypi or do we have to pin 6.7.0.2018.9 as pypi doesn't allow to re-upload the same package?

**Comment by pgbidkar** [comment] 2018-09-12 09:15
@saenzpa Please start using latest version 6.7.0.2018.9. 
pypi doesnt allow re-uploading same package.

**Comment by thomasshanks** [comment] 2018-09-13 04:35
Can you reupload the original 6.7.0 release as 6.7.0.<YEAR>.<MONTH>?  We need the original release.

**Comment by ajaytripathi** [comment] 2018-09-18 19:34
We too need the original release. Can we upload old and the new one with the fixes, if someone wants to upgrade.

**Comment by tianhao64** [comment] 2018-09-20 18:41
@thomasshanks @ajaytripathi We can't uploaded the original 6.7.0 package. It has some critical issues that has to be addressed. Please use the new version instead for 6.7 release. Apologies for any issues and inconvenience this may cause.

**Comment by jeking3** [comment] 2018-10-25 11:42
The project was updated to v6.7.1 on Oct 23.

**Comment by jeking3** [comment] 2018-12-19 01:10
@cpollard0 please close this.

**Closed** 2023-01-26 20:25 UTC
