### ISSUE TITLE
parseError for pbmContent.placementSolver.PbmCheckCompatibility

### ISSUE THREAD

**Issue by mamatadesai** [vmware/pyvmomi#550] opened 2017-05-24 02:53 UTC
Hello,

We are trying to automate some vasa3 test cases with pyVmomi but running into parseError and would like some help on the issue. Please see attached sample code. On line 44, pbmContent.placementSolver.PbmCheckCompatibility(profile=sp.profileId) runs into parseError. The python program, it's error stack, and SOAP traces in sps log are attached.

Also appreciate if anyone can give pointers on how to log/save to file the SOAP exchanges between the python program and the vCenter.  Going into the debugger, the HTTPResponse object seems to be all blanks.

(Pdb) data
<http.client.HTTPResponse object at 0x7f6b7cb32198>
(Pdb) data.read().decode('utf-8')
''
(Pdb) data.length
3034
[PbmCheckCompatibility.zip](https://github.com/vmware/pyvmomi/files/1024267/PbmCheckCompatibility.zip)

Thanks,
Mamata

**Comment by mamatadesai** [comment] 2017-05-24 05:23
Attached is a debug from pyCharm, it shows the response has an empty payload.
![capture](https://cloud.githubusercontent.com/assets/28913776/26387953/628d19c2-4006-11e7-8ae6-198c41e92485.PNG)

**Comment by prziborowski** [comment] 2017-05-24 21:52
I don't know about why the payload is empty. A theory is that it has already been read out of the file/socket by that time.

I think the issue is we are somehow missing the data type for PbmPlacementMatchingResources in PbmObjects.py

Can you try adding:
```
CreateDataType("pbm.placement.MatchingResources", "PbmPlacementMatchingResources", "vmodl.DynamicData", "pbm.version.version11", None)
```
to the file, perhaps above:
```
CreateDataType("pbm.placement.MatchingReplicationResources", "PbmPlacementMatchingReplicationResources", "pbm.placement.MatchingResources", "pbm.version.version11", [("replicationGroup", "vim.vm.replication.ReplicationGroupId[]", "pbm.version.version11", F_OPTIONAL)])
```

@tianhao64 : do you know if this is a generation issue or it for some reason got excluded because the base type doesn't have any fields?

**Comment by mamatadesai** [comment] 2017-05-25 01:18
@prziborowski  That worked!!  Fantastic, thank you!

**Comment by tianhao64** [comment] 2017-05-31 05:28
Fixed by https://github.com/vmware/pyvmomi/pull/555

**Closed by tianhao64** 2017-05-31 05:28 UTC
