### ISSUE TITLE
I cannot get value hostAccessManager, after Update esxi (hostAccessManager is None)

### ISSUE THREAD

**Issue by kovalal** [vmware/pyvmomi#826] opened 2019-08-21 14:53 UTC
connect = SmartConnect(host=host, user=user, pwd=password, sslContext=myssl)
content = connect.RetrieveContent()
object_view =content.viewManager.CreateContainerView(content.rootFolder, [vim.HostSystem], True)
result = object_view.view[0].configManager.hostAccessManager

result is None

**Comment by pgbidkar** [comment] 2019-08-21 15:15
Hi @kovalal ,
I dont see this issue. tried same code you shared

```from pyVim.connect import SmartConnectNoSSL
from pyVmomi import vim

connect = SmartConnectNoSSL(host='', user='VCUser', pwd='VCPass')
content = connect.RetrieveContent()
object_view =content.viewManager.CreateContainerView(content.rootFolder, [vim.HostSystem], True)
result = object_view.view[0].configManager.hostAccessManager
print(result)```

I get this output
```'vim.host.HostAccessManager:hostAccessManager-47'```

Please can you check if your object_view is populated correctly

**Comment by kovalal** [comment] 2019-08-22 05:59
> Please can you check if your object_view is populated correctly

Object is populated, some properties are correct, but hostAcessManager in property configManager is None. I tried get it from content.rootFolder.chieldEntity[0].hostFolder.chieldEntity[0].host[0].configManager, but there was the same result.

**Comment by pgbidkar** [comment] 2019-08-22 06:10
Thanks for sharing info.

But I am not able to reproduce the issue. Please can you share ESX/VC version?

**Comment by kovalal** [comment] 2019-08-22 06:59
Esxi version 6.7.0 Update 1.  I tried connect into vc (6.7.0) and get info about hosts, but there was hostAcessManager = None. I checked privileges, user has "System.View" privilege.
I made mistake! I`m sorry, but path is "content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0].configManager"

**Comment by kovalal** [comment] 2019-08-22 07:05
> But I am not able to reproduce the issue. Please can you share ESX/VC version?
Esxi version - 6.7.0 U1 I tried connect into vc (6.7.0) and get info about hosts, but there was hostAcessManager = None. I also checked privileges, user has System.View privilege.
I`m sorry, but  i`ve made mistake, path is content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0].configManager

**Comment by pgbidkar** [comment] 2019-08-22 07:31
> > But I am not able to reproduce the issue. Please can you share ESX/VC version?
> 
> Esxi version - 6.7.0 U1 I tried connect into vc (6.7.0) and get info about hosts, but there was hostAcessManager = None. I also checked privileges, user has System.View privilege.
> I`m sorry, but i`ve made mistake, path is content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0].configManager

Is it fixed now?

**Comment by kovalal** [comment] 2019-08-22 07:33
> > > But I am not able to reproduce the issue. Please can you share ESX/VC version?
> > 
> > 
> > Esxi version - 6.7.0 U1 I tried connect into vc (6.7.0) and get info about hosts, but there was hostAcessManager = None. I also checked privileges, user has System.View privilege.
> > I`m sorry, but i`ve made mistake, path is content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0].configManager
> 
> Is it fixed now?

No

**Comment by pgbidkar** [comment] 2019-08-22 08:25
Tried with VC 6.7 & 6.7.1 issue is not reproducible.
Path used is
```
result = object_view.view[0].configManager.hostAccessManager
```
Value returned is 
```
'vim.host.HostAccessManager:hostAccessManager-46'
```

**Closed** 2023-01-26 21:05 UTC
