### ISSUE TITLE
AttributeError: Query , while using pyVim.task.waitfortask

### ISSUE THREAD

**Issue by Zorrom** [vmware/pyvmomi#997] opened 2022-12-06 11:18 UTC
### Describe the bug

Hi Team,
  We are trying to attach an existing data.vmdk harddisk to our deployed vm and during that time, we are facing the following issue  and our code is written as follows
  
```
task = browser.Search(dirname, search_spec)
pyVim.task.WaitForTask(task)

```

The dirname and searchspec values are as follows

```
dirname='[datastore1] data-disks'

search_spec='(vim.host.DatastoreBrowser.SearchSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   query = (vim.host.DatastoreBrowser.Query) [
      (vim.host.DatastoreBrowser.FolderQuery) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) []
      },
      (vim.host.DatastoreBrowser.Query) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) []
      }
   ],
   details = (vim.host.DatastoreBrowser.FileInfo.Details) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      fileType = true,
      fileSize = false,
      modification = false,
      fileOwner = false
   },
   searchCaseInsensitive = <unset>,
   matchPattern = (str) [
      'vm01-data.vmdk'
   ],
   sortFoldersFirst = true
}'
```

So when the code `pyVim.task.WaitForTask(task)` is getting called, it is throwing the following error 

```
File "/root/datastore_add.py", line 208, in list
pyVim.task.WaitForTask(task)

File "/usr/local/lib/python3.6/dist-packages/pyVim/task.py", line 126, in WaitForTask
filter = CreateFilter(pc, task)

File "/usr/local/lib/python3.6/dist-packages/pyVim/task.py", line 266, in CreateFilter
return CreateTasksFilter(pc, [task])

File "/usr/local/lib/python3.6/dist-packages/pyVim/task.py", line 276, in CreateTasksFilter
vmodl.Query.PropertyCollector.ObjectSpec(obj=task) for task in tasks

File "/usr/local/lib/python3.6/dist-packages/pyVim/task.py", line 276, in <listcomp>
vmodl.Query.PropertyCollector.ObjectSpec(obj=task) for task in tasks

File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 249, in getattr
raise AttributeError(attr)

AttributeError: Query

```

This issue is happening when we try to add existing data.vmdk disk to our vm after redeployment. Please let us know what is going wrong here

Thanks and Regards,
Azhar

### Reproduction steps

1. Try to attach data-vmdk to a vm after redeployment using pyVim.task.WaitForTask code
...

### Expected behavior

Expecting pyVmomi to attach the existing data.vmdk harddisk and proceed to next step. The output should show as follows

```
2022-09-02 05:07:27,489 GenerateVM-1 vm.hardware.Disk.create(vm, {type : None, ide : None, scsi : None, sata : None, backing : {type : VMDK_FILE, vmdk_file : [datastore1] /vm01-data.vmdk}, new_vmdk : None}) -> 2001
2022-09-02 05:07:27,589 GenerateVM-1 vm.hardware.Disk.get(vm-30499, 2001) -> Info(
backing=BackingInfo(
type='VMDK_FILE',
vmdk_file='[datastore1] datadisks/vm01-data.vmdk',
),
capacity=214748364800,
ide=None,
label='Hard disk 2',
sata=None,
scsi=ScsiAddressInfo(
bus=0,
unit=1,
),
type='SCSI',
),
```

_No response_

**Comment by Zorrom** [comment] 2022-12-06 12:45
Hi Team, 
   We found that our code is working when we use vCenter 7.x and Pyvomi with version 7.0.3 . And if we use vCenter 7.x with pyVomi as 8.0.0.1 then we are getting this error. Please let us know if the Pyvmomi version of 8.x is having backward compatibility issues with 7.x vcenters

**Comment by cghioc** [comment] 2022-12-07 07:34
Hi Zorom,

This looks like a duplicate of https://github.com/vmware/pyvmomi/issues/993 fixed in commit https://github.com/vmware/pyvmomi/commit/4251afb3a0feab483704973a63e34fc4a21fc9e5

**Comment by Zorrom** [comment] 2022-12-07 08:10
@cghioc , Thanks for your response. May I know when do we get this fix rolled out to global users. The link says (12/11/2022), does that mean 11-Dec-2022 ?

**Comment by DanielDraganov** [comment] 2022-12-16 10:33
[Maintenance Patch 1 for 8.0](https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1.1) has just been released.
I'm closing this one as it's duplicating #993.

**Closed by DanielDraganov** 2022-12-16 10:33 UTC
Labels: bug
