### ISSUE TITLE
pyVmomi.VmomiSupport.UnknownWsdlTypeError: 'ContentLibrary'

### ISSUE THREAD

**Issue by arunpatyal** [vmware/pyvmomi#764] opened 2019-02-06 07:28 UTC
Getting the below error after performing any action on Content Inventory such as create a new content inventory object. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyvmomi-6.7.1.2018.12-py3.6.egg/pyVmomi/SoapAdapter.py", line 509, in ParseData
  File "../Modules/pyexpat.c", line 414, in StartElement
  File "/usr/local/lib/python3.6/dist-packages/pyvmomi-6.7.1.2018.12-py3.6.egg/pyVmomi/SoapAdapter.py", line 719, in StartElementHandler
  File "/usr/local/lib/python3.6/dist-packages/pyvmomi-6.7.1.2018.12-py3.6.egg/pyVmomi/VmomiSupport.py", line 1192, in GuessWsdlType
pyVmomi.VmomiSupport.UnknownWsdlTypeError: 'ContentLibrary'

Debugged and determined that the event EventEx and TaskEvent are being generated which generates this error.

Steps:
1. Create a new content inventory.
2. Call eventCollector.ReadNextEvents, get all events or EventEx and TaskEvent 

vsphere version 6.5

**Comment by pgbidkar** [comment] 2019-02-06 07:34
Hi @arunpatyal ,  Please can you check SdkRepo https://github.com/vmware/vsphere-automation-sdk-python for ContentLibrary APIs.

Thanks

**Comment by arunpatyal** [comment] 2019-02-06 09:28
thanks @pgbidkar , the use case is to get all the events. With the above error it fails intermittently. I am not specifically interested in Content Library.

**Comment by pgbidkar** [comment] 2019-02-06 09:33
Hi @arunpatyal Please can you check the issue https://github.com/vmware/pyvmomi/issues/746. looks like similar to this. I have shared code snippet. Try if that helps

Thanks

**Comment by arunpatyal** [comment] 2019-02-06 09:41
This is exactly I am doing it:
The event_type_list below lists all the events to be fetched.

It works properly until below steps are taken:

    1. Create a new content inventory.

    2. Call eventCollector.ReadNextEvents, get all events or EventEx and TaskEvent

if not ssl_verify:
        context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        context.verify_mode = ssl.CERT_NONE
    elif ssl_capath:
        context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        context.verify_mode = ssl.CERT_REQUIRED
        context.load_verify_locations(capath=ssl_capath)

    if not ssl_verify and ssl_capath:
        logfile.write(logPrefix + "Incorrect configuration, proceeding with "
                       "ssl verification disabled.\n")
    password = args.password
    if args.pass_encrypted:
        cipher_suite = Fernet(args.key)
        uncipher_text = (cipher_suite.decrypt(bytes(args.password, "utf-8")))
        password = bytes(uncipher_text).decode("utf-8") # convert to string

    serverConn = SmartConnect(host=args.server,
                           user=args.user,
                           pwd=password,
                           port=args.port,
                           sslContext=context if not ssl_verify or ssl_capath else None)
    atexit.register(Disconnect, serverConn)
    separator = ",,,"
    evtCount = 0
    byTime = vim.event.EventFilterSpec.ByTime(beginTime=beginTime, endTime=endTime)
    filterSpec = vim.event.EventFilterSpec(eventTypeId=event_type_list, time=byTime)
    eventManager = serverConn.content.eventManager
    eventCollector = eventManager.CreateCollectorForEvents(filterSpec)
    eventCollector.RewindCollector()
    lastReadTime = None
    while True:
        packetContent = ""
        eventsArray = eventCollector.ReadNextEvents(maxCount=400)

**Comment by pgbidkar** [comment] 2019-02-15 05:36
Hi @arunpatyal Please can you share some more details how You did first step 
1. Create a new content inventory.

2. Call eventCollector.ReadNextEvents, get all events or EventEx and TaskEvent

Issue is not reproducible. Tried creating content library and read events. Issue is not reproducible

Thanks

**Comment by arunpatyal** [comment] 2019-02-15 07:29
<img width="562" alt="image" src="https://user-images.githubusercontent.com/10919488/52841145-7bab0c80-3121-11e9-8295-bb160307c05f.png">

**Comment by pgbidkar** [comment] 2019-02-15 07:36
Yes did the same steps. Couldn't reproduce the issue. 
Tried with 6.5, 6.5U1 & 6.7

Thanks

**Comment by pgbidkar** [comment] 2019-03-04 06:42
Hi @arunpatyal , Any updates? is issue still reproducible?

Thanks

**Comment by pgbidkar** [comment] 2019-03-12 06:05
Hi @arunpatyal Closing the issue. Please open new or reopen if issue still not resolved

Thanks

**Closed by pgbidkar** 2019-03-12 06:05 UTC

**Comment by arunpatyal** [comment] 2019-03-12 06:49
@pgbidkar We are still facing the issue with same steps, we are avoiding the issue by skipping this event.
